// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://komvxasfembeswebgnjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbXZ4YXNmZW1iZXN3ZWJnbmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNzUzNTAsImV4cCI6MjA4NTk1MTM1MH0.SrYiK9ZKZjCYk2lemQTrHhrZ1XQhRqQqFsCJtuujTdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});